### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by themultiplexer** [dheera/ros-pwm-pca9685#1]
Hi @dheera 

I am pretty new to ROS and trying to build a RPi-Robot to learn it.
I have [this](https://www.amazon.de/gp/product/B072N8G7Y9/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1) PCA9685 based PWM board and I run ROS Melodic on Debian Buster and everything works fine (including a camera). The board has address 0x40 so the default parameters are probably correct.

`libi2c-dev` is installed and I try to start your node like this:

```bash
rosrun pwm_pca9685 pca9685_node
``` 
But it segfaults:
```
[ INFO] [1585099217.457893949]: initializing
[ INFO] [1585099217.477227357]: starting
Segmentation fault
```

(gdb) backtrace
```
#0  0x00016158 in pwm_pca9685::PCA9685Activity::set(unsigned char, unsigned short) ()
#1  0x00016ae0 in pwm_pca9685::PCA9685Activity::spinOnce() ()
#2  0x00015bd4 in main ()
```

Maybe you know why this happens or you can tell me how to properly debug it.

**Comment by themultiplexer** [comment]
Oh wait, today after restarting the bot and the master it does not crash with a segmentation fault anymore :+1:
